title: easy-deposit-agreement-creator
description: >-
  JSON-based deposit service.
baseurl: "/easy-deposit-agreement-creator"
github_username: DANS-KNAW

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
